#!/bin/bash

# This ensures all executables build and all tests pass before a commit
# goes through.

set -v
set -e

go1.21.0 test
# need to wait until I can update my core system to 1.21 for this.
# golangci-lint run

echo Build succeeds.
exit 0


